### ISSUE TITLE
references for algorithm

### ISSUE THREAD

**Issue by mdsumner** [ecohealthalliance/fasterize#17]
I thought it worth collating any related references for this method, both for the need for a link for CRAN, and for general usage. I'd write this into a vignette or the readme if you prefer. 

This paper, seems to fit the bill as a suitable peer-reviewed ref: 

http://www2.tku.edu.tw/~tkjse/2-4/2-4-1.pdf

Good details on scan-line behaviours at horizontals, shared vertices: 
http://www.cs.mun.ca/av/old/teaching/cg/notes/raster_poly.pdf

Course on rasterization, in PPT format: 
https://www.cs.virginia.edu/~asb/teaching/cs445-fall06/slides/09-rasterization.ppt

"Conservative and Tiled Rasterization Using a Modified Triangle Setup" - possibly related to discussion at https://github.com/ecohealthalliance/fasterize/issues/1#issuecomment-297874763
https://users.aalto.fi/~ailat1/publications/am2005jgt_paper.pdf

Another lecture Polygon Scan Conversion and Z-Buffering: 

http://www.vis.uky.edu/~ryang/Teaching/cs535-2012spr/Lectures/11-scan.pdf

**Comment by noamross** [comment]
Good refs to have! Especially because we'll want to use some of them for line and point rasterization eventually.  Here are notes that I referenced in that past: https://dl.dropbox.com/s/q4o4f0rab0iiyqt/polyfill.zip . The professor had taken them down but emailed them to me.  

I'll close this now that we have Wylie (1967) in the description and docs.
