### ISSUE TITLE
Implement methods for sp types

### ISSUE THREAD

**Issue by noamross** [ecohealthalliance/fasterize#2]
This should be pretty simple, just convert sp to sf.  Need to set up S3 dispatch for this.

**Comment by mpadge** [comment]
@noamross seems like a good place to cross-fertilise your grand work on fasterize with [`osmdata`](https://github.com/osmdatar/osmdata) - submitted to [`ropensci`](https://github.com/ropensci/onboarding/issues/103). You're going from `sf` to other formats; `osmdata` does conversions in the other directions, absent direct `Depends` or `Imports` of the beast that is `sf`.

Full `sp` code is also included [here](https://github.com/osmdatar/osmdata/blob/master/src/osmdata-sp.cpp) - feel free to crib all you like, but note that `Rcpp` dis-mantling of `S4` objects is considerably slower than simple `S3` ones, so your results aren't likely to be as impressive as for `sf`. `osmdata` has some timing comparisons [here](https://github.com/osmdatar/osmdata/wiki/Timing-benchmarks), which don't even include `sp` because it's orders of magnitude slower.
